# --- !Ups
CREATE TABLE IF NOT EXISTS TEST_RECORDS(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	GENDER INTEGER NOT NULL,
	ADDRESS VARCHAR(255),
	BIRTHDAY DATE
) DEFAULT CHARSET=UTF8;

# --- !Downs
DROP TABLE IF EXISTS TEST_RECORDS;
